###
GET http://localhost:5000/models/rf/info

###
GET http://localhost:5000/models/1067

###
GET http://localhost:8080/api/predictor_models/predict?smiles=c1ccccc1&model_id=1065

###
GET http://localhost:8080/api/predictor_models/predict?smiles=c1ccccc1&model_id=1065

###
POST http://localhost:8080/api/predictor_models/predict
Content-Type: application/json

{
  "smiles": ["c1ccccc1", "CCCCC"],
  "model_id": 1065
}